apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "todo-app.fullname" . }}-statefulset
spec:
  serviceName: "mongodb"
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels: 
      app: {{ .Values.mongodb.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.labels.app }}
    spec:
      containers:
      - name: {{ .Values.mongodb.labels.app }}
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        ports:
        - containerPort: {{ .Values.mongodb.ports.containerPort }}
        volumeMounts:
        - name: {{ .Values.mongodb.volumeClaim.name }}
          mountPath: {{ .Values.mongodb.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.mongodb.volumeClaim.name }}
    spec:
      accessModes: {{ .Values.mongodb.volumeClaim.accessModes }}
      resources:
        requests:
          storage: {{ .Values.mongodb.volumeClaim.resources.storage }}