apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-service
spec:
  selector:
    app: {{ .Values.todoService.labels.app }}
  ports:
  - port: {{ .Values.todoService.ports.port }}
    targetPort: {{ .Values.todoService.ports.targetPort }}
